### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [masonc15/wsl-notify-zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by masonc15** [comment]
Done. (9f365dcef1c1ac75210607e6fe448b0334567d1e)
Thanks!  Curious how you found this, automated Github search?

**Comment by unixorn** [comment]
Nothing that sophisticated. I basically do a search every day or two for zsh themes, plugins and completions.
